run-mmul:
	./gradlew :matrix-multiplication:run

run-dphils:
	./gradlew :dining-philosophers:run

run-deadlock:
	./gradlew :deadlock:run -PmainClass=examples.Deadlock

run-rsc-ordering:
	./gradlew :deadlock:run -PmainClass=examples.ResourceOrdering

test:
	./gradlew clean test